create table mock_data
(
    internal_id          serial primary key,
    id                   int,
    customer_first_name  text          not null,
    customer_last_name   text          not null,
    customer_age         int           not null,
    customer_email       text unique,
    customer_country     text          not null,
    customer_postal_code text,
    customer_pet_type    text          not null,
    customer_pet_name    text          not null,
    customer_pet_breed   text          not null,
    seller_first_name    text          not null,
    seller_last_name     text          not null,
    seller_email         text unique,
    seller_country       text          not null,
    seller_postal_code   text,
    product_name         text          not null,
    product_category     text          not null,
    product_price        numeric(5, 2) not null,
    product_quantity     int           not null,
    sale_date            date          not null,
    sale_customer_id     int           not null,
    sale_seller_id       int           not null,
    sale_product_id      int           not null,
    sale_quantity        int           not null,
    sale_total_price     numeric(5, 2) not null,
    store_name           text          not null,
    store_location       text          not null,
    store_city           text          not null,
    store_state          text,
    store_country        text          not null,
    store_phone          text unique,
    store_email          text unique,
    pet_category         text          not null,
    product_weight       numeric(5, 2) not null,
    product_color        text          not null,
    product_size         text          not null,
    product_brand        text          not null,
    product_material     text          not null,
    product_description  text          not null,
    product_rating       numeric(5, 2) not null,
    product_reviews      int           not null,
    product_release_date date          not null,
    product_expiry_date  date          not null,
    supplier_name        text          not null,
    supplier_contact     text          not null,
    supplier_email       text unique,
    supplier_phone       text unique,
    supplier_address     text          not null,
    supplier_city        text          not null,
    supplier_country     text          not null
);