FROM sbtscala/scala-sbt:eclipse-temurin-alpine-25.0.1_8_1.12.11_3.8.3 AS build

WORKDIR /app
COPY build.sbt .
COPY project/plugins.sbt project/plugins.sbt
COPY src src
COPY common common
COPY consumer consumer
COPY producer producer
RUN sbt consumer/assembly

FROM flink:2.2.1-java17
COPY --from=build /app/consumer/target/scala-3.3.7/consumer.jar /opt/flink/lib/consumer.jar